version: "3.5"

services:
  bot:
    build: .
    container_name: finance_bot
    command: python ./TelegramBot/main.py
    ports:
      - 80:80
    environment:
      DATABASE_URL: "mysql://user:mypassword@mysql_db/telegrambot"
    volumes:
      - ./:/app
    depends_on:
      - mysql_db
    networks:
      - app-network
  mysql_db:
    restart: always
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Vladik_1"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "mypassword"
      MYSQL_DATABASE: "telegrambot"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network
volumes:
  mysql:
networks:
  app-network:

